

// ServicesListItem Page
export const FETCH_SERVICES = 'FETCH_SERVICES';




export const SERVICE_HOME = 'SERVICE_HOME'
export const SERVICE_ALBUMS = 'SERVICE_ALBUMS'
export const SERVICE_DRESSES = 'SERVICE_DRESSES'
export const SERVICE_VIDEOS = 'SERVICE_VIDEOS'
export const SERVICE_PRICELIST = 'SERVICE_PRICELIST'
export const SERVICE_PRICE_ALBUMS = 'SERVICE_PRICE_ALBUMS'
export const SERVICE_PRICE_VIDEOS = 'SERVICE_PRICE_VIDEO'
export const SERVICE_PRICE_INCLUSIVE = 'SERVICE_PRICE_INCLUSIVE'
export const SERVICE_OTHERS = 'SERVICE_OTHERS'

export const SERVICE_EDIT_ALBUM = 'SERVICE_EDIT_ALBUM'
export const SERVICE_EDIT_DRESS = 'SERVICE_EDIT_DRESS'
export const SERVICE_EDIT_VIDEO = 'SERVICE_EDIT_VIDEO'
export const SERVICE_EDIT_PRICELIST = 'SERVICE_EDIT_PRICELIST'
export const SERVICE_EDIT_PRICE_ALBUM = 'SERVICE_EDIT_PRICE_ALBUM'
export const SERVICE_EDIT_PRICE_VIDEO = 'SERVICE_EDIT_PRICE_VIDEO'
export const SERVICE_EDIT_PRICE_INCLUSIVE = 'SERVICE_EDIT_PRICE_INCLUSIVE'
export const SERVICE_EDIT_OTHERS = 'SERVICE_EDIT_OTHERS'


export const SERVICE_ADDNEW_ALBUM = 'SERVICE_ADDNEW_ALBUM'
export const SERVICE_ADDNEW_DRESS = 'SERVICE_ADDNEW_DRESS'
export const SERVICE_ADDNEW_VIDEO = 'SERVICE_ADDNEW_VIDEO'
export const SERVICE_ADDNEW_PRICELIST = 'SERVICE_ADDNEW_PRICELIST'
export const SERVICE_ADDNEW_PRICE_ALBUM = 'SERVICE_ADDNEW_PRICE_ALBUM'
export const SERVICE_ADDNEW_PRICE_VIDEO = 'SERVICE_ADDNEW_PRICE_VIDEO'
export const SERVICE_ADDNEW_PRICE_INCLUSIVE = 'SERVICE_ADDNEW_PRICE_INCLUSIVE'
export const SERVICE_ADDNEW_OTHERS = 'SERVICE_ADDNEW_OTHERS'

export const MSG_NO_SELECTED_DELETED = 'Vui lòng chọn mục muốn xóa !'





